compliance/urls.py
from django.conf.urls.defaults import *
from compliance import views, ajax

urlpatterns = patterns('',
    url(r'^$', views.index, name='compliance'), 
    url(r'^policies/$', views.policy_manager, name='compliance_policies'),
    url(r'^policies/upload/', ajax.upload_policy, name='compliance_policy_upload'),
    url(r'^policies/download/(\d+)', ajax.download_policy, name='compliance_policy_download'),
    url(r'^policies/delete/(\d+)', ajax.delete_policy, name='compliance_policy_delete'),
    url(r'^scans/$', views.scan_manager, name='compliance_scans'),
    url(r'^scans/schedule/$', views.scan_schedules, name='compliance_scan_schedule'),
    url(r'^scans/schedule/create', views.create_scan_schedule, name='compliance_create_scan_schedule'),
    url(r'^scans/configs/$', views.scan_configurations, name='compliance_scan_configurations'),
    url(r'^scans/configs/create', ajax.create_scanconfig, name='compliance_create_scan_config'),
    url(r'^scans/configs/delete/(\d+)', ajax.delete_scanconfig, name='compliance_delete_scan_config'),
    url(r'^scans/targets/$', views.scan_targets, name='compliance_scan_targets'),
    url(r'^scans/targets/create', ajax.create_targets, name='compliance_create_targets'),
    url(r'^scans/targets/delete/(\d+)', ajax.delete_targets, name='compliance_delete_targets'),
    url(r'^scans/templates/$', views.scan_templates, name='compliance_scan_templates'),
    url(r'^scans/templates/create', ajax.create_template, name='compliance_create_template'),
    url(r'^scans/templates/delete/(\d+)', ajax.delete_template, name='compliance_delete_template'),
)

urls.py
import django.views.static
import os
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    (r'^userprofile/', include('userprofile.urls')),
    (r'^devices/', include('devices.urls')),
    (r'^vulns/', include('vulnerabilities.urls')),
    (r'^scans/', include('scans.urls')),
    (r'^plugins/', include('plugins.urls')),
    (r'^falsepositives/', include('falsepositives.urls')),
    (r'^subscriptions/', include('subscriptions.urls')),
    (r'^compliance/', include('compliance.urls')),
    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
        # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    (r'^', include('reaper.sarim.urls')),
    
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^site_media/(?P<path>.*)$', django.views.static.serve,
            {'document_root': os.path.join(settings.PROJECT_ROOT,'common','static')}, name='static'),
        )

compliance/models.py
from django.db import models

# Create your models here.
class Policy(models.Model):
    TYPE_CHOICES = (
            ('WI', 'Windows'),
            ('UN', 'Unix'),
            ('DB', 'Database'),
            ('WF', 'Windows File'),
            )
    name = models.CharField(max_length=255)
    data = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    type = models.CharField(max_length=2, choices=TYPE_CHOICES)
    hash = models.CharField(max_length=40, unique=True)

class Template(models.Model):
    name = models.CharField(max_length=255)
    data = models.TextField()
    hash = models.CharField(max_length=40, unique=True)

class ScanConfig(models.Model):
    name = models.CharField(max_length=255)
    plugins = models.ManyToManyField('plugins.Plugin')
    policies = models.ManyToManyField('compliance.Policy')
    template = models.ForeignKey('compliance.Template')

class Target(models.Model):
    name = models.CharField(max_length=255)
    targets = models.TextField()
    hash = models.CharField(max_length=40, unique=True)

class Scan(models.Model):
    scan_config = models.ForeignKey('compliance.ScanConfig')
    targets = models.ForeignKey('compliance.Target')
    start = models.DateTimeField()
    stop = models.DateTimeField()

class Result(models.Model):
    scan = models.ForeignKey('compliance.Scan')
    ip_address = models.ForeignKey('devices.IpAddress')
    plugin = models.ForeignKey('plugins.Plugin')
    type = models.CharField(max_length = 25)
    description = models.TextField()

class ScheduledScan(models.Model):
    scan = models.ForeignKey('compliance.Scan', null=True)
    scan_config = models.ForeignKey('compliance.ScanConfig')
    targets = models.ForeignKey('compliance.Target')
    name = models.CharField(max_length=80)
    time = models.TimeField()
    sunday = models.BooleanField(default=False)
    monday = models.BooleanField(default=False)
    tuesday = models.BooleanField(default=False)
    wednesday = models.BooleanField(default=False)
    thursday = models.BooleanField(default=False)
    friday = models.BooleanField(default=False)
    saturday = models.BooleanField(default=False)

plugins/models.py
from django.db import models
from django.contrib.contenttypes import generic
from utils.fields import SparseField
from sarim.models import Comment

# Create your models here.
class Plugin(models.Model):
    def __init__(self, *args, **kwargs):
        super(Plugin,self).__init__(*args, **kwargs)
        self.parsed = False
        self.descparts = {}

    def __parse_desc(self):
        #get everything ready to work on
        if self.parsed:
            return
        desc = self.description
        ldesc = desc.lower()
        index = []
        #words to look for
        words = ['synopsis','description','solution','risk factor']
        #build a list of tuples of format (<word position>, <word>)
        for word in words:
            try:
                index.append( (ldesc.index(word), word) )
            except:
                index.append( (-1, word) )
        #sort the aforementioned list according to word position
        import operator
        sindex = sorted(index, key=operator.itemgetter(0))

        for pos, word in sindex:
            #Get the tuple's position in the list of tuples
            mappos = sindex.index( (pos, word) )
            #-1 means the word wasn't found...
            if pos == -1:
                #All this does is go find the next word without a -1 position
                #and copy all of the text from the start of the description to the
                #first position found
                if word == 'description':
                    x = -1
                    for i in range(mappos,len(sindex)):
                        if sindex[i][0] != -1:
                            x = sindex[i][0]
                    s = desc[0:x]
                else:
                    continue
            else:
                if mappos == len(sindex)-1:
                    s = desc[pos+len(word):]
                else:
                    s = desc[pos+len(word):sindex[mappos+1][0]]

            #The nessus plugin info has some stupid escaping going on
            s = s.replace(':\\n\\n', '')
            s = s.replace('\\n', ' ')
            s = s.replace(': ', '', 1)
            #Take care of dictionary names with spaces in them
            self.descparts[word.replace(' ', '')] = s

        self.parsed = True

    def __get_synopsis(self):
        self.__parse_desc()
        if self.descparts.has_key('synopsis'):
            return self.descparts['synopsis']
        else:
            return None
    def __get_desc(self):
        self.__parse_desc()
        if self.descparts.has_key('description'):
            return self.descparts['description']
        else:
            return None
    def __get_solution(self):
        self.__parse_desc()
        if self.descparts.has_key('solution'):
            return self.descparts['solution']
        else:
            return None
    def __get_riskfactor(self):
        self.__parse_desc()
        if self.descparts.has_key('riskfactor'):
            return self.descparts['riskfactor']
        else:
            return None

    desc = property(__get_desc)
    synopsis = property(__get_synopsis)
    solution = property(__get_solution)
    riskfactor = property(__get_riskfactor)

    def __unicode__(self):
        return u'nessus plugin {0}'.format(self.nessusid)
    id = models.IntegerField(primary_key=True)
    digest = models.CharField(max_length=192, primary_key=True)
    nessusid = models.IntegerField()
    name = models.TextField()
    version = models.CharField(max_length=96)
    summary = models.TextField()
    family = models.CharField(max_length=192)
    category = models.CharField(max_length=96)
    risk = models.CharField(max_length=384)
    cveid = models.TextField(blank=True)
    bugtraqid = models.TextField(blank=True)
    xref = models.TextField(blank=True)
    top20cves = models.TextField(blank=True)
    description = models.TextField(blank=True)
    configfile = models.TextField(blank=True)
    entered = models.DateTimeField(auto_now_add=True)
    comments = generic.GenericRelation('sarim.Comment')
    class Meta:
        managed = False
        ordering = ['-entered']
        db_table = u'plugin'
        get_latest_by = u'entered'

class PluginDump(models.Model):
    id = models.IntegerField(primary_key=True)
    plugincount = models.IntegerField()
    pluginsadded = models.IntegerField(null=True, blank=True)
    pluginlist = SparseField(blank=True)
    digest = models.CharField(unique=True, max_length=120)
    source = models.ForeignKey('sarim.Source', db_column='sourceid')
    starttime = models.DateTimeField()
    endtime = models.DateTimeField(null=True, blank=True)
    plugins = models.ManyToManyField('Plugin', through='PluginDumpPlugin')
    comments = generic.GenericRelation('sarim.Comment')
    class Meta:
        managed = False
        db_table = u'plugindump'

class PluginDumpPlugin(models.Model):
    plugindump = models.ForeignKey('PluginDump', db_column='plugindumpid', primary_key=True)
    plugin = models.ForeignKey('Plugin', db_column='pluginid')
    class Meta:
        managed = False
        db_table = u'plugindumpplugin'

compliance/views.py
from django.http import *
from django.shortcuts import render_to_response
from django.template import RequestContext
from compliance.models import *
from plugins.models import *
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
import datetime as dt
from django.core.urlresolvers import reverse

# Create your views here.
@user_passes_test(lambda u: u.is_staff == 1)
def index(request):
    days_back = request.user.get_profile().default_days_back

    render_dict = {
            'pagetitle': 'Compliance',
            'results': Result.objects.all() #.order_by('-scan__stop'),
            #'results': Result.objects.filter( scan__stop__gte = dt.date.today() - dt.timedelta(days=7) ),
            }

    return render_to_response('compliance_results.html', render_dict, context_instance=RequestContext(request))

@user_passes_test(lambda u: u.is_staff == 1)
def policy_manager(request):
    #need upload, download, view all policies
    render_dict = {
            'pagetitle': 'Compliance',
            'subtitle': 'Policies',
            'policy_types': Policy.TYPE_CHOICES,
            'policies': Policy.objects.all().order_by('-timestamp', 'name'),
            }

    if request.GET.has_key('show_add_form') and request.GET['show_add_form'] == '1':
        render_dict['show_new'] = True

    return render_to_response('compliance_policies.html', render_dict, context_instance=RequestContext(request))

@user_passes_test(lambda u: u.is_staff == 1)
def scan_manager(request):
    render_dict = {
            'pagetitle': 'Compliance',
            'subtitle': 'Scans',
            'scans': Scan.objects.all().order_by('-stop'),
            }

    return render_to_response('compliance_scans.html', render_dict, context_instance=RequestContext(request))

@user_passes_test(lambda u: u.is_staff == 1)
def create_scan_schedule(request):
    day_on = lambda x: request.POST.has_key(x) and request.POST[x] == 'on'
    try:
        name = request.POST['name']
        m = day_on('mon')
        t = day_on('tue')
        w = day_on('wed')
        th = day_on('thu')
        fr = day_on('fri')
        sa = day_on('sat')
        su = day_on('sun')
        hour = request.POST['hour']
        minute = request.POST['minute']
        if int(hour) not in range(24):
            raise ValueError('Hour out of range')
        if int(minute) not in range(60):
            raise ValueError('Minute out of range')
        if not (m or t or w or th or fr or sa or su):
            raise ValueError('At least one day must be checked')
    except Exception, e:
        request.user.message_set.create(message='Unable to schedule scan: %s' % str(e))
        return HttpResponseRedirect( reverse('compliance_scan_schedule') )
    
    zf = lambda x: str.zfill(str(x), 2)
    scan_schedule = ScheduledScan()
    scan_schedule.time = "%s:%s:00" % (zf(hour), zf(minute))
    scan_schedule.monday = m
    scan_schedule.tuesday = t
    scan_schedule.wednesday = w
    scan_schedule.thursday = th
    scan_schedule.friday = fr
    scan_schedule.saturday = sa
    scan_schedule.sunday = su
    scan_schedule.name = name
    scan_schedule.save()

    request.user.message_set.create(message='Scheduled successfully!')
    return HttpResponseRedirect( reverse('compliance_scan_schedule') )

@user_passes_test(lambda u: u.is_staff == 1)
def scan_schedules(request):
    render_dict = {
            'pagetitle': 'Compliance',
            'subtitle': 'Scans',
            'schedules': ScheduledScan.objects.all().order_by('name'),
            }
    
    if request.GET.has_key('show_add_form') and request.GET['show_add_form'] == '1':
        render_dict['show_new'] = True

    return render_to_response('compliance_scan_schedule.html', render_dict, context_instance=RequestContext(request))

@user_passes_test(lambda u: u.is_staff == 1)
def scan_configurations(request):
    render_dict = {
            'pagetitle': 'Compliance',
            'subtitle': 'Scans',
            'wi_policies': Policy.objects.filter(type="WI").order_by('name'),
            'wf_policies': Policy.objects.filter(type="WF").order_by('name'),
            'un_policies': Policy.objects.filter(type="UN").order_by('name'),
            'db_policies': Policy.objects.filter(type="DB").order_by('name'),
            'configs': ScanConfig.objects.all().order_by('name'),
            }

    if request.GET.has_key('show_add_form') and request.GET['show_add_form'] == '1':
        render_dict['show_new'] = True

    return render_to_response('compliance_scan_configurations.html', render_dict, context_instance=RequestContext(request))

@user_passes_test(lambda u: u.is_staff == 1)
def scan_targets(request):
    render_dict = {
            'pagetitle': 'Compliance',
            'subtitle': 'Scans',
            'targets': Target.objects.all(),
            }
    if request.GET.has_key('show_add_form') and request.GET['show_add_form'] == '1':
        render_dict['show_new'] = True

    return render_to_response('compliance_scan_targets.html', render_dict, context_instance=RequestContext(request))

@user_passes_test(lambda u: u.is_staff == 1)
def scan_templates(request):
    render_dict = {
            'pagetitle': 'Compliance',
            'subtitle': 'Scans',
            'templates': Template.objects.all(),
            }

    if request.GET.has_key('show_add_form') and request.GET['show_add_form'] == '1':
        render_dict['show_new'] = True

    return render_to_response('compliance_scan_templates.html', render_dict, context_instance=RequestContext(request))

compliance/templates/compliance_policies.html
{% extends 'base.html' %}

{% block extra_head %}
<script>
    $(document).ready(function() {
        $('tr.result').toggle(
            function() {
                $(this).next().show();
            },
            function() {
                $(this).next().hide();
            }
        );
        $('#show-new').toggle(
            function() {
                $('#upload_form').slideDown();
            },
            function() {
                $('#upload_form').slideUp();
            }
        );
    {% if show_new %}
    $('#show-new').click();
    {% endif %}
    });
</script>
{% endblock %}

{% block sidebar %}
{% include 'compliance_sidebar.html' %}
{% endblock %}

{% block main_body %}
<h1>Compliance Scan Policies</h1>
{% for message in messages %}
    {% if forloop.first %}
    <ul id="messages">
    {% endif %}
        <li class="warning"> {{ message }} </li>
    {% if forloop.last %}
    </ul>
    {% endif %}
{% endfor %}

<h2>Upload new policy <a id='show-new' href="#">[+]</a></h2>
<div class='hidden' id='upload_form'>
    <form method='post' action='{% url compliance_policy_upload %}' enctype="multipart/form-data">
        <table>
            <tr>
                <td>
                    <label for='filename'>Policy Name</label>
                </td>
                <td>
                    <input style="width: 150px;" id='filename' type='text' size=255 name='filename'></input>
                </td>
            </tr>
            <tr>
                <td>
                    <label for='type'>Policy Type</label>
                </td>
                <td>
                    <select name='type' id='type'>
                        {% for k,v in policy_types %}
                        <option value='{{k}}'>{{ v }}</option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    <label for='file'>Select File</label>
                </td>
                <td>
                    <input id='file' type='file' name='file'></input>
                </td>
            </tr>
            <tr>
                <td colspan=2>
                    <input style='float: right;' type="submit" value="Upload" name="btnUpload"></input>
                </td>
            </tr>
        </table>
    </form>
</div>
<h2>Existing Policies</h2>
{% for policy in policies %}
    {% if forloop.first %}
    <table class='block'>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Uploaded</th>
        </tr>
    {% endif %}
        <tr class='result'>
            <td>{{policy.name}}</td>
            <td>{{policy.get_type_display}}</td>
            <td>{{policy.timestamp|date:'F j, Y'}}</td>
        </tr>
        <tr style='background-color: #E4DFD1;' class='hidden'>
            <td colspan=3>
                <a style='float: right;' href="{% url compliance_policy_delete policy.id %}">Delete</a>
                <p>
                <a href="{% url compliance_policy_download policy.id %}">Download</a><br>
                SHA: {{ policy.hash }}
                </p>
            </td>
        </tr>
    {% if forloop.last %}
    </table>
    {% endif %}
{% endfor %}

{% endblock %}

compliance/templates/compliance_results.html
{% extends 'base.html' %}
{% load deviceutils %}

{% block extra_head %}
<script type="text/javascript">
    $(document).ready(function() {
        var visible = null;
        $("tr.result").toggle(
            function() {
                $(this).next().show();
                },
            function() {
                $(this).next().hide();
                }
            );
    }
    );
</script>
{% endblock %}

{% block sidebar %}
{% include 'compliance_sidebar.html' %}
{% endblock %}

{% block main_body %}
<h1>Compliance Scan Results</h1>
<h2>All compliance results from the past {{ user.get_profile.default_days_back }} days.</h2>
<table class='block'>
    {% for i in results %}
    {% if forloop.first %}
    <tr>
        <th>Host</th>
        <th>Plugin</th>
        <th>Type</th>
        <th>Description</th>
    </tr>
    {% endif %}
        <tr class="result">
            <td>{{ i.ip_address|to_hostname }}</td>
            {% if i.plugin %}<td>{{ i.plugin }}</td>{%else%}<td>N/A</td>{%endif%}
            <td>{{ i.type }}</td>
            <td>{{ i.description|truncatewords:5 }}</td>
        </tr>
        <tr class="hidden">
            <td class='result' colspan=4>
            <pre width=75 class="safe">
{{i.description}}
            </pre>
            </td>
        </tr>
    {% empty %}
        <tr><td><center>There are no compliance issues.</center></td></tr>
    {% endfor %}
</table>
{% endblock %}

compliance/templates/compliance_scan_configurations.html
{% extends 'base.html' %}
{% load utils %}

{% block sidebar %}
{% include 'compliance_sidebar.html' %}
{% endblock %}

{% block extra_head %}
<script>
    function l2h(a) {
        var h = {};
        for(var i=0; i<a.length; i++)
            h[a[i]] = '';
        return h;
    }

    function select_length(a) {
        var i = 0;
        for(var z; z < a.options.length; z++)
            if(a.options[i].selected)
                i++

        return i;
    }

    var selectedCount = [];
    $(document).ready(function () {
        $('.select5').change(
            function() {
                if(select_length(this) <= 5) {
                    selectedCount[this] = [];
                    for(var z; z < this.options.length; z++)
                        if(this.options[i].selected)
                            selectedCount[this].push(i);
                } else {
                    for(var i; i < selectedCount[this].length - 5; i++)
                        this.options[selectedCount[this].pop()].selected = false;
                }
            }
        );
        $('tr.result').toggle(
            function() {
                $(this).next().show();
            },
            function() {
                $(this).next().hide();
            }
            );
        $('#show-new').toggle(
            function() {
                $('#newform').slideDown();
            },
            function() {
                $('#newform').slideUp();
            }
            );
        {% if show_new %}
            $('#show-new').click();
        {% endif %}
        });
</script>
{% endblock %}


{% block main_body %}
<h1>Compliance Scan Configurations</h1>
<h2>New Scan Configuration <a href="#" id='show-new'>[+]</a></h2>
<div id="newform" class="hidden">
    <form action="{% url compliance_create_scan_config %}" method="POST">
        <table>
            <tr>
                <td><label for="name">Name</label></td>
                <td><input name="name"id="name" type="textbox"></input></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><label for="select-template">Template</label></td>
                <td>
                    <select id='select-template' name="template">
                        <option value="-1"> -------- </option>
                        {% for t in templates %}
                        <option value="{{ t.id }}">{{ t.name }}</option>
                        {% endfor %}
                    </select>
                </td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td colspan=4><h3>Policies<sub>(max 5 per column)</sub></h3></td>
            </tr>
            <tr>
                <th>{% if wi_policies %}Windows{% endif %}</th>
                <th>{% if wf_policies %}Windows File{% endif %}</th>
                <th>{% if un_policies %}Unix{% endif %}</th>
                <th>{% if db_policies %}Database{% endif %}</th>
            </tr>
            <tr>
                <td class='group-select'>
                    {% if wi_policies %}
                    {% for i in 5|nrange %}
                    <select name="wi-policies{{i}}">
                        <option value="-1"> ---------- </option>
                        {% for p in wi_policies %}
                        <option value="{{ p.id }}">{{ p.name }}</option>
                        {% endfor %}
                    </select>
                    {% endfor %}
                    {% endif %}
                </td>
                <td class='group-select'>
                    {% if wf_policies %}
                    {% for i in 5|nrange %}
                    <select name="wf-policies{{i}}">
                        <option value="-1"> ---------- </option>
                        {% for p in wf_policies %}
                        <option value="{{ p.id }}">{{ p.name }}</option>
                        {% endfor %}
                    </select>
                    {% endfor %}
                    {% endif %}
                </td>
                <td class='group-select'>
                    {% if un_policies %}
                    {% for i in 5|nrange %}
                    <select name="un-policies{{i}}">
                        <option value="-1"> ---------- </option>
                        {% for p in un_policies %}
                        <option value="{{ p.id }}">{{ p.name }}</option>
                        {% endfor %}
                    </select>
                    {% endfor %}
                    {% endif %}
                </td>
                <td class='group-select'>
                    {% if db_policies %}
                    {% for i in 5|nrange %}
                    <select name="db-policies{{i}}">
                        <option value="-1"> ---------- </option>
                        {% for p in db_policies %}
                        <option value="{{ p.id }}">{{ p.name }}</option>
                        {% endfor %}
                    </select>
                    {% endfor %}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td colspan=2><input style="float:right;" type="submit" value="Submit"></input></td>
                <td colspan=2></td>
            </tr>
        </table>
    </form>
</div>

<h2>Existing Scan Configurations</h2>
<table class='block'>
    {% for config in configs %}
        {% if forloop.first %}
        <tr>
            <th>Name</th>
            <th># Plugins</th>
            <th># Policies</th>
            <th>Template Name</th>
        </tr>
        {% endif %}
        <tr class='result'>
            <td>{{ config.name }}</td>
            <td>{{ config.plugin_set.count }}</td>
            <td>{{ config.policy_set.count }}</td>
            <td>{{ config.template__name }}</td>
        </tr> 
        <tr class='hidden'>
            <td colspan=4 class='result'>
                <a style='float: right;' href="{% url compliance_delete_scan_config config.id %}">Delete</a>
            </td>
        </tr>

        {% empty %}
        <tr>
            <td style='text-align: center;' colspan=4>
            There are no scan configurations
            </td>
        </tr>
    {% endfor %}
</table>
{% endblock %}

compliance/templates/compliance_scan_targets.html
{% extends 'base.html' %}

{% block extra_head %}
<script>
    $(document).ready(function() {
        $('tr.result').toggle(
            function() {
                $(this).next().show();
            },
            function() {
                $(this).next().hide();
            }
        );
        $('#show-new').toggle(
            function() {
                $('#newform').slideDown();
            },
            function() {
                $('#newform').slideUp();
            }
        );
    {% if show_new %}
    $('#show-new').click();
    {% endif %}
    });
</script>
{% endblock %}

{% block sidebar %}
{% include 'compliance_sidebar.html' %}
{% endblock %}

{% block main_body %}
<h1>Compliance Scan Targets</h1>
<h2>New Target Definition <a href="#" id='show-new'>[+]</a></h2>
<div style='margin-left: 10px;' id='newform' class='hidden'>
    <form action='{% url compliance_create_targets %}' method='POST'>
        <label style='margin-right: 1em;' for='name'>Name</label><input name='name' type='text'></input><br/>
        <br/>
        <label for='targetdata'>Targets data</label><br/>
        <textarea style="width: 40em; height: 20em;" name='targetdata'></textarea>
        <br/>
        <input type='submit' value='Submit'/>
    </form>
</div>

<h2>Existing Targets</h2>
<table class='block'>
    {% for target in targets %}
    {% if forloop.first %}
    <tr>
        <th>Name</th>
        <th>Hash</th>
    </tr>
    {% endif %}
    <tr class='result'>
        <td>{{ target.name }}</td>
        <td>{{ target.hash }}</td>
    </tr>
    <tr class='hidden'>
        <td colspan=2 class='result'>
            <a style='float: right;' href="{% url compliance_delete_targets target.id %}">Delete</a>
            <pre class="safe">
{{ target.targets }}
            </pre>
        </td>
    </tr>

    {% empty %}
    <tr>
        <td style='text-align: center;' colspan=4>
            There are no target definitions
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %} 

compliance/templates/compliance_scan_templates.html
{% extends 'base.html' %}

{% block extra_head %}
<script>
    $(document).ready(function() {
        $('tr.result').toggle(
            function() {
                $(this).next().show();
            },
            function() {
                $(this).next().hide();
            }
        );
        $('#show-new').toggle(
            function() {
                $('#newform').slideDown();
            },
            function() {
                $('#newform').slideUp();
            }
        );

    {% if show_new %}
    $('#show-new').click();
    {% endif %}
    });
</script>
{% endblock %}

{% block sidebar %}
{% include 'compliance_sidebar.html' %}
{% endblock %}

{% block main_body %}
<h1>Compliance Scan Templates</h1>
<h2>New Template <a href="#" id='show-new'>[+]</a></h2>
<div style='margin-left: 10px;' id='newform' class='hidden'>
    <form action='{% url compliance_create_template %}' method='POST'>
        <label style='margin-right: 1em;' for='name'>Name</label><input name='name' type='text'></input><br/>
        <br/>
        <label for='data'>Template data</label><br/>
        <textarea style="width: 40em; height: 20em;" name='data'></textarea>
        <br/>
        <input type='submit' value='Submit'/>
    </form>
</div>

<h2>Existing Templates</h2>
<table class='block'>
    {% for template in templates %}
    {% if forloop.first %}
    <tr>
        <th>Name</th>
        <th>Hash</th>
    </tr>
    {% endif %}
    <tr class='result'>
        <td>{{ template.name }}</td>
        <td>{{ template.hash }}</td>
    </tr>
    <tr class='hidden'>
        <td colspan=2 class='result'>
            <a style='float: right;' href="{% url compliance_delete_template template.id %}">Delete</a>
            <pre class="safe">
{{ template.data }}
            </pre>
        </td>
    </tr>

    {% empty %}
    <tr>
        <td style='text-align: center;' colspan=4>
            There are no templates
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %} 

compliance/templates/compliance_sidebar.html
<li><a href="{% url compliance %}">Scan Results</a></li>
<li><hr></li>
<li><a href="{% url compliance_policies %}">Policy Manager</a></li>
<li><a href="{% url compliance_scans %}">Scan Manager</a></li>
{% ifequal subtitle 'Scans' %}
<li>
    <ul>
        <li><a href="{% url compliance_scan_schedule %}">Schedule</a></li>
        <li><a href="{% url compliance_scan_configurations %}">Configurations</a></li>
        <li><a href="{% url compliance_scan_targets %}">Targets</a></li>
        <li><a href="{% url compliance_scan_templates %}">Templates</a></li>
    </ul>
</li>
{% endifequal %}